// src/lib/components/scanner/CropEditor.svelte
<script lang="ts">
	import { Button } from 'carbon-components-svelte';
	import type { CropRect } from '$lib/stores/scanner.svelte';

	interface Props {
		imageUrl: string;
		initialCrop: CropRect | null;
		onchange: (crop: CropRect) => void;
		onconfirm: () => void;
		oncancel: () => void;
	}

	let { imageUrl, initialCrop, onchange, onconfirm, oncancel }: Props = $props();

	let containerEl = $state<HTMLDivElement | null>(null);
	let canvasEl = $state<HTMLCanvasElement | null>(null);
	let imgEl = $state<HTMLImageElement | null>(null);
	let imgLoaded = $state(false);

	/** Displayed image bounds within the container */
	let imgRect = $state({ x: 0, y: 0, w: 0, h: 0 });

	/** Normalized crop (0–1) */
	let crop = $state<CropRect>({ x: 0, y: 0, width: 1, height: 1 });

	$effect(() => {
		if (initialCrop) {
			crop = { ...initialCrop };
		}
	});

	/** Active drag state */
	let dragHandle = $state<string | null>(null);
	let dragStart = $state({ px: 0, py: 0, crop: { x: 0, y: 0, width: 0, height: 0 } });

	const HANDLE_SIZE = 24;
	const MIN_CROP = 0.05;

	function updateImgRect() {
		if (!containerEl || !imgEl || !imgLoaded) return;
		const cw = containerEl.clientWidth;
		const ch = containerEl.clientHeight;
		const iw = imgEl.naturalWidth;
		const ih = imgEl.naturalHeight;
		if (!iw || !ih) return;

		const scale = Math.min(cw / iw, ch / ih);
		const w = iw * scale;
		const h = ih * scale;
		imgRect = { x: (cw - w) / 2, y: (ch - h) / 2, w, h };
		drawOverlay();
	}

	$effect(() => {
		if (imgLoaded && containerEl) {
			updateImgRect();
			const ro = new ResizeObserver(() => updateImgRect());
			ro.observe(containerEl);
			return () => ro.disconnect();
		}
	});

	$effect(() => {
		// Redraw whenever crop changes
		void crop.x;
		void crop.y;
		void crop.width;
		void crop.height;
		drawOverlay();
	});

	function drawOverlay() {
		if (!canvasEl || !containerEl) return;
		const cw = containerEl.clientWidth;
		const ch = containerEl.clientHeight;
		canvasEl.width = cw;
		canvasEl.height = ch;

		const ctx = canvasEl.getContext('2d');
		if (!ctx) return;

		ctx.clearRect(0, 0, cw, ch);

		// Crop rect in pixel coords
		const cx = imgRect.x + crop.x * imgRect.w;
		const cy = imgRect.y + crop.y * imgRect.h;
		const cWidth = crop.width * imgRect.w;
		const cHeight = crop.height * imgRect.h;

		// Dim outside crop
		ctx.fillStyle = 'rgba(0, 0, 0, 0.6)';
		ctx.fillRect(0, 0, cw, ch);
		ctx.clearRect(cx, cy, cWidth, cHeight);

		// Dashed crop border
		ctx.strokeStyle = '#ffffff';
		ctx.lineWidth = 2;
		ctx.setLineDash([6, 4]);
		ctx.strokeRect(cx, cy, cWidth, cHeight);
		ctx.setLineDash([]);

		// Corner handles
		const corners = [
			{ hx: cx, hy: cy },
			{ hx: cx + cWidth, hy: cy },
			{ hx: cx, hy: cy + cHeight },
			{ hx: cx + cWidth, hy: cy + cHeight }
		];
		ctx.fillStyle = '#ffffff';
		for (const c of corners) {
			ctx.beginPath();
			ctx.arc(c.hx, c.hy, 6, 0, Math.PI * 2);
			ctx.fill();
		}

		// Edge handles (midpoints, small squares)
		const edges = [
			{ hx: cx + cWidth / 2, hy: cy },
			{ hx: cx + cWidth / 2, hy: cy + cHeight },
			{ hx: cx, hy: cy + cHeight / 2 },
			{ hx: cx + cWidth, hy: cy + cHeight / 2 }
		];
		for (const e of edges) {
			ctx.fillRect(e.hx - 4, e.hy - 4, 8, 8);
		}
	}

	function getHandleAt(px: number, py: number): string | null {
		const cx = imgRect.x + crop.x * imgRect.w;
		const cy = imgRect.y + crop.y * imgRect.h;
		const cw = crop.width * imgRect.w;
		const ch = crop.height * imgRect.h;
		const hs = HANDLE_SIZE / 2;

		// Corners
		if (Math.abs(px - cx) < hs && Math.abs(py - cy) < hs) return 'tl';
		if (Math.abs(px - (cx + cw)) < hs && Math.abs(py - cy) < hs) return 'tr';
		if (Math.abs(px - cx) < hs && Math.abs(py - (cy + ch)) < hs) return 'bl';
		if (Math.abs(px - (cx + cw)) < hs && Math.abs(py - (cy + ch)) < hs) return 'br';

		// Edges
		if (Math.abs(px - (cx + cw / 2)) < hs && Math.abs(py - cy) < hs) return 'top';
		if (Math.abs(px - (cx + cw / 2)) < hs && Math.abs(py - (cy + ch)) < hs) return 'bottom';
		if (Math.abs(px - cx) < hs && Math.abs(py - (cy + ch / 2)) < hs) return 'left';
		if (Math.abs(px - (cx + cw)) < hs && Math.abs(py - (cy + ch / 2)) < hs) return 'right';

		// Move (inside crop)
		if (px >= cx && px <= cx + cw && py >= cy && py <= cy + ch) return 'move';

		return null;
	}

	function pointerCoords(e: PointerEvent): { px: number; py: number } {
		if (!containerEl) return { px: 0, py: 0 };
		const rect = containerEl.getBoundingClientRect();
		return { px: e.clientX - rect.left, py: e.clientY - rect.top };
	}

	function handlePointerDown(e: PointerEvent) {
		const { px, py } = pointerCoords(e);
		const handle = getHandleAt(px, py);
		if (!handle) return;
		dragHandle = handle;
		dragStart = { px, py, crop: { ...crop } };
		(e.target as Element)?.setPointerCapture?.(e.pointerId);
		e.preventDefault();
	}

	function handlePointerMove(e: PointerEvent) {
		if (!dragHandle) return;
		e.preventDefault();
		const { px, py } = pointerCoords(e);
		const dx = (px - dragStart.px) / imgRect.w;
		const dy = (py - dragStart.py) / imgRect.h;
		const s = dragStart.crop;

		let nx = crop.x;
		let ny = crop.y;
		let nw = crop.width;
		let nh = crop.height;

		if (dragHandle === 'move') {
			nx = clamp(s.x + dx, 0, 1 - s.width);
			ny = clamp(s.y + dy, 0, 1 - s.height);
			nw = s.width;
			nh = s.height;
		} else {
			const isLeft = dragHandle === 'tl' || dragHandle === 'bl' || dragHandle === 'left';
			const isRight = dragHandle === 'tr' || dragHandle === 'br' || dragHandle === 'right';
			const isTop = dragHandle === 'tl' || dragHandle === 'tr' || dragHandle === 'top';
			const isBottom = dragHandle === 'bl' || dragHandle === 'br' || dragHandle === 'bottom';

			if (isLeft) {
				const maxDx = s.width - MIN_CROP;
				const d = clamp(dx, -s.x, maxDx);
				nx = s.x + d;
				nw = s.width - d;
			} else if (isRight) {
				nw = clamp(s.width + dx, MIN_CROP, 1 - s.x);
			} else {
				nx = s.x;
				nw = s.width;
			}

			if (isTop) {
				const maxDy = s.height - MIN_CROP;
				const d = clamp(dy, -s.y, maxDy);
				ny = s.y + d;
				nh = s.height - d;
			} else if (isBottom) {
				nh = clamp(s.height + dy, MIN_CROP, 1 - s.y);
			} else {
				ny = s.y;
				nh = s.height;
			}
		}

		crop = { x: nx, y: ny, width: nw, height: nh };
		onchange(crop);
	}

	function handlePointerUp() {
		dragHandle = null;
	}

	function clamp(v: number, min: number, max: number): number {
		return Math.min(max, Math.max(min, v));
	}
</script>

<div class="crop-editor">
	<div
		class="canvas-container"
		bind:this={containerEl}
	>
		<img
			src={imageUrl}
			alt="Crop target"
			class="crop-image"
			bind:this={imgEl}
			onload={() => { imgLoaded = true; updateImgRect(); }}
		/>
		<canvas
			bind:this={canvasEl}
			class="overlay-canvas"
			onpointerdown={handlePointerDown}
			onpointermove={handlePointerMove}
			onpointerup={handlePointerUp}
			onpointercancel={handlePointerUp}
		></canvas>
	</div>

	<div class="crop-actions">
		<Button kind="secondary" size="small" on:click={oncancel}>Cancel</Button>
		<Button kind="primary" size="small" on:click={onconfirm}>Confirm</Button>
	</div>
</div>

<style>
	.crop-editor {
		display: flex;
		flex-direction: column;
		width: 100%;
		height: 100%;
		background: #000;
	}

	.canvas-container {
		flex: 1;
		position: relative;
		overflow: hidden;
		touch-action: none;
	}

	.crop-image {
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		max-width: 100%;
		max-height: 100%;
		object-fit: contain;
		pointer-events: none;
		user-select: none;
	}

	.overlay-canvas {
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		cursor: crosshair;
	}

	.crop-actions {
		display: flex;
		justify-content: center;
		gap: 0.75rem;
		padding: 0.75rem 1rem;
		background: var(--cds-layer-01, #0d0d0d);
	}
</style>

// src/components/scanner/CropEditor.tsx
import { useRef, useState, useEffect, useCallback } from 'react';
import { Button } from '@carbon/react';
import type { QuadCrop, Point } from '@/stores/scanner';
import './CropEditor.css';

interface CropEditorProps {
  imageUrl: string;
  initialCrop: QuadCrop | null;
  onChange: (crop: QuadCrop) => void;
  onConfirm: () => void;
  onCancel: () => void;
}

const CORNER_RADIUS = 10;
const HIT_RADIUS = 24;
const DEFAULT_QUAD: QuadCrop = { tl: { x: 0, y: 0 }, tr: { x: 1, y: 0 }, br: { x: 1, y: 1 }, bl: { x: 0, y: 1 } };
type CornerKey = 'tl' | 'tr' | 'br' | 'bl';

function clamp(v: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, v));
}

function dist(ax: number, ay: number, bx: number, by: number): number {
  return Math.hypot(ax - bx, ay - by);
}

/** Canvas-based 4-corner quadrilateral crop editor with pinch-to-zoom */
export default function CropEditor({ imageUrl, initialCrop, onChange, onConfirm, onCancel }: CropEditorProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const imgRef = useRef<HTMLImageElement>(null);

  const [imgLoaded, setImgLoaded] = useState(false);
  const [scale, setScale] = useState(1.0);
  const imgRectRef = useRef({ x: 0, y: 0, w: 0, h: 0 });
  const quadRef = useRef<QuadCrop>(initialCrop ? { ...initialCrop, tl: { ...initialCrop.tl }, tr: { ...initialCrop.tr }, br: { ...initialCrop.br }, bl: { ...initialCrop.bl } } : { ...DEFAULT_QUAD });
  const dragRef = useRef<{ corner: CornerKey; } | null>(null);
  const pinchRef = useRef<{ startDist: number; startScale: number } | null>(null);

  useEffect(() => {
    if (initialCrop) {
      quadRef.current = { tl: { ...initialCrop.tl }, tr: { ...initialCrop.tr }, br: { ...initialCrop.br }, bl: { ...initialCrop.bl } };
      drawOverlay();
    }
  }, [initialCrop]); // eslint-disable-line react-hooks/exhaustive-deps

  const updateImgRect = useCallback(() => {
    const container = containerRef.current;
    const img = imgRef.current;
    if (!container || !img || !imgLoaded) return;
    const cw = container.clientWidth;
    const ch = container.clientHeight;
    const iw = img.naturalWidth;
    const ih = img.naturalHeight;
    if (!iw || !ih) return;

    const s = Math.min(cw / iw, ch / ih);
    const w = iw * s;
    const h = ih * s;
    imgRectRef.current = { x: (cw - w) / 2, y: (ch - h) / 2, w, h };
    drawOverlay();
  }, [imgLoaded]); // eslint-disable-line react-hooks/exhaustive-deps

  /** Convert normalized quad point to canvas pixel coords */
  const toCanvas = useCallback((p: Point): { cx: number; cy: number } => {
    const ir = imgRectRef.current;
    return { cx: ir.x + p.x * ir.w, cy: ir.y + p.y * ir.h };
  }, []);

  const drawOverlay = useCallback(() => {
    const canvas = canvasRef.current;
    const container = containerRef.current;
    if (!canvas || !container) return;
    const cw = container.clientWidth;
    const ch = container.clientHeight;
    canvas.width = cw;
    canvas.height = ch;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const q = quadRef.current;
    const tl = toCanvas(q.tl);
    const tr = toCanvas(q.tr);
    const br = toCanvas(q.br);
    const bl = toCanvas(q.bl);

    // Step 1: Fill entire canvas with dark overlay
    ctx.fillStyle = 'rgba(0, 0, 0, 0.6)';
    ctx.fillRect(0, 0, cw, ch);

    // Step 2: Cut out the quad shape
    ctx.save();
    ctx.globalCompositeOperation = 'destination-out';
    ctx.beginPath();
    ctx.moveTo(tl.cx, tl.cy);
    ctx.lineTo(tr.cx, tr.cy);
    ctx.lineTo(br.cx, br.cy);
    ctx.lineTo(bl.cx, bl.cy);
    ctx.closePath();
    ctx.fillStyle = 'rgba(0, 0, 0, 1)';
    ctx.fill();
    ctx.restore();

    // Step 3: Draw quad outline
    ctx.strokeStyle = '#ffffff';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(tl.cx, tl.cy);
    ctx.lineTo(tr.cx, tr.cy);
    ctx.lineTo(br.cx, br.cy);
    ctx.lineTo(bl.cx, bl.cy);
    ctx.closePath();
    ctx.stroke();

    // Step 4: Draw corner circles
    const corners = [tl, tr, br, bl];
    for (const c of corners) {
      ctx.beginPath();
      ctx.arc(c.cx, c.cy, CORNER_RADIUS, 0, Math.PI * 2);
      ctx.fillStyle = '#ffffff';
      ctx.fill();
      ctx.strokeStyle = '#0f62fe';
      ctx.lineWidth = 2;
      ctx.stroke();
    }

    // Step 5: Draw edge midpoint dots (visual guide only)
    const midpoints = [
      { mx: (tl.cx + tr.cx) / 2, my: (tl.cy + tr.cy) / 2 },
      { mx: (tr.cx + br.cx) / 2, my: (tr.cy + br.cy) / 2 },
      { mx: (br.cx + bl.cx) / 2, my: (br.cy + bl.cy) / 2 },
      { mx: (bl.cx + tl.cx) / 2, my: (bl.cy + tl.cy) / 2 },
    ];
    for (const m of midpoints) {
      ctx.beginPath();
      ctx.arc(m.mx, m.my, 3, 0, Math.PI * 2);
      ctx.fillStyle = 'rgba(255, 255, 255, 0.7)';
      ctx.fill();
    }
  }, [toCanvas]);

  // ResizeObserver
  useEffect(() => {
    if (!imgLoaded || !containerRef.current) return;
    updateImgRect();
    const ro = new ResizeObserver(() => updateImgRect());
    ro.observe(containerRef.current);
    return () => ro.disconnect();
  }, [imgLoaded, updateImgRect]);

  function findClosestCorner(px: number, py: number): CornerKey | null {
    const q = quadRef.current;
    const keys: CornerKey[] = ['tl', 'tr', 'br', 'bl'];
    let closest: CornerKey | null = null;
    let minDist = HIT_RADIUS;

    for (const key of keys) {
      const { cx, cy } = toCanvas(q[key]);
      const d = dist(px, py, cx, cy);
      if (d < minDist) {
        minDist = d;
        closest = key;
      }
    }
    return closest;
  }

  function pointerCoords(e: React.PointerEvent): { px: number; py: number } {
    if (!containerRef.current) return { px: 0, py: 0 };
    const rect = containerRef.current.getBoundingClientRect();
    return { px: e.clientX - rect.left, py: e.clientY - rect.top };
  }

  const handlePointerDown = (e: React.PointerEvent) => {
    const { px, py } = pointerCoords(e);
    const corner = findClosestCorner(px, py);
    if (!corner) return;
    dragRef.current = { corner };
    (e.target as Element)?.setPointerCapture?.(e.pointerId);
    e.preventDefault();
  };

  const handlePointerMove = (e: React.PointerEvent) => {
    const drag = dragRef.current;
    if (!drag) return;
    e.preventDefault();
    const { px, py } = pointerCoords(e);
    const ir = imgRectRef.current;
    if (ir.w === 0 || ir.h === 0) return;

    const nx = clamp((px - ir.x) / ir.w, 0, 1);
    const ny = clamp((py - ir.y) / ir.h, 0, 1);

    quadRef.current = {
      ...quadRef.current,
      [drag.corner]: { x: nx, y: ny }
    };
    drawOverlay();
    onChange({ ...quadRef.current });
  };

  const handlePointerUp = () => {
    dragRef.current = null;
  };

  // Pinch-to-zoom handlers
  const handleTouchStart = (e: React.TouchEvent) => {
    if (e.touches.length === 2) {
      const dx = e.touches[0].clientX - e.touches[1].clientX;
      const dy = e.touches[0].clientY - e.touches[1].clientY;
      pinchRef.current = { startDist: Math.hypot(dx, dy), startScale: scale };
    }
  };

  const handleTouchMove = (e: React.TouchEvent) => {
    if (e.touches.length === 2 && pinchRef.current) {
      const dx = e.touches[0].clientX - e.touches[1].clientX;
      const dy = e.touches[0].clientY - e.touches[1].clientY;
      const d = Math.hypot(dx, dy);
      const newScale = clamp(pinchRef.current.startScale * (d / pinchRef.current.startDist), 0.5, 3.0);
      setScale(newScale);
    }
  };

  const handleTouchEnd = () => {
    pinchRef.current = null;
  };

  const resetScale = useCallback(() => {
    setScale(1.0);
  }, []);

  const handleImgLoad = () => {
    setImgLoaded(true);
    updateImgRect();
  };

  return (
    <div className="crop-editor">
      <div
        className="canvas-container"
        ref={containerRef}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
        onTouchCancel={handleTouchEnd}
      >
        <img
          src={imageUrl}
          alt="Crop target"
          className="crop-image"
          ref={imgRef}
          onLoad={handleImgLoad}
          style={{ transform: `translate(-50%, -50%) scale(${scale})` }}
        />
        <canvas
          ref={canvasRef}
          className="overlay-canvas"
          onPointerDown={handlePointerDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerCancel={handlePointerUp}
        />
      </div>

      <div className="crop-actions">
        <Button kind="secondary" size="sm" onClick={() => { resetScale(); onCancel(); }}>Cancel</Button>
        <Button kind="primary" size="sm" onClick={() => { resetScale(); onConfirm(); }}>Confirm</Button>
      </div>
    </div>
  );
}
