// src/components/manipulator/Toolbar.tsx
import { Button } from '@carbon/react';
import {
  DocumentAdd,
  CheckboxChecked,
  Rotate,
  Copy,
  DocumentBlank,
  TrashCan,
  SplitScreen,
  Minimize,
  Undo,
  Redo,
  Download,
  Printer,
  Share
} from '@carbon/icons-react';
import './Toolbar.css';

interface ToolbarProps {
  pageCount: number;
  selectedCount: number;
  canUndo: boolean;
  canRedo: boolean;
  isLoading: boolean;
  maxPages: number;
  onAdd: () => void;
  onRotate: () => void;
  onDuplicate: () => void;
  onInsertBlank: () => void;
  onDelete: () => void;
  onSplit: () => void;
  onCompress: () => void;
  onUndo: () => void;
  onRedo: () => void;
  onExport: () => void;
  onPrint: () => void;
  onShare: () => void;
  onSelectAll: () => void;
}

/** Horizontal toolbar with grouped page operations */
export default function Toolbar({
  pageCount, selectedCount, canUndo, canRedo, isLoading, maxPages,
  onAdd, onRotate, onDuplicate, onInsertBlank, onDelete,
  onSplit, onCompress, onUndo, onRedo, onExport, onPrint, onShare, onSelectAll
}: ToolbarProps) {
  const atPageLimit = pageCount >= maxPages;
  const noSelection = selectedCount === 0;
  const noPages = pageCount === 0;

  return (
    <div className="toolbar" role="toolbar" aria-label="Page operations" aria-orientation="horizontal">
      <div className="toolbar-group">
        <Button kind="ghost" size="sm" renderIcon={DocumentAdd} iconDescription="Add files" disabled={isLoading} onClick={onAdd}>
          <span className="btn-label">Add</span>
        </Button>
        <Button kind="ghost" size="sm" renderIcon={CheckboxChecked} iconDescription="Select all" disabled={noPages} onClick={onSelectAll}>
          <span className="btn-label">Select All</span>
        </Button>
      </div>
      <div className="toolbar-divider" />
      <div className="toolbar-group">
        <Button kind="ghost" size="sm" renderIcon={Rotate} iconDescription="Rotate" disabled={noSelection} onClick={onRotate}>
          <span className="btn-label">Rotate</span>
        </Button>
        <Button kind="ghost" size="sm" renderIcon={Copy} iconDescription="Duplicate" disabled={noSelection} onClick={onDuplicate}>
          <span className="btn-label">Duplicate</span>
        </Button>
        <Button kind="ghost" size="sm" renderIcon={DocumentBlank} iconDescription="Insert blank page" disabled={atPageLimit || isLoading} onClick={onInsertBlank}>
          <span className="btn-label">Blank</span>
        </Button>
        <Button kind="ghost" size="sm" renderIcon={TrashCan} iconDescription="Delete" disabled={noSelection} onClick={onDelete}>
          <span className="btn-label">Delete</span>
        </Button>
      </div>
      <div className="toolbar-divider" />
      <div className="toolbar-group">
        <Button kind="ghost" size="sm" renderIcon={SplitScreen} iconDescription="Split" disabled={noPages} onClick={onSplit}>
          <span className="btn-label">Split</span>
        </Button>
        <Button kind="ghost" size="sm" renderIcon={Minimize} iconDescription="Compress" disabled={noSelection} onClick={onCompress}>
          <span className="btn-label">Compress</span>
        </Button>
      </div>
      <div className="toolbar-spacer" />
      <div className="toolbar-group">
        <Button kind="ghost" size="sm" renderIcon={Undo} iconDescription="Undo" disabled={!canUndo} onClick={onUndo} hasIconOnly />
        <Button kind="ghost" size="sm" renderIcon={Redo} iconDescription="Redo" disabled={!canRedo} onClick={onRedo} hasIconOnly />
      </div>
      <div className="toolbar-group">
        <Button kind="primary" size="sm" renderIcon={Download} disabled={noPages || isLoading} onClick={onExport}>
          <span className="btn-label">Export</span>
        </Button>
        <Button kind="ghost" size="sm" renderIcon={Printer} iconDescription="Print" disabled={noPages || isLoading} onClick={onPrint}>
          <span className="btn-label">Print</span>
        </Button>
        <Button kind="ghost" size="sm" renderIcon={Share} iconDescription="Share" disabled={noPages || isLoading} onClick={onShare}>
          <span className="btn-label">Share</span>
        </Button>
      </div>
    </div>
  );
}

// src/lib/components/manipulator/Toolbar.svelte
<script lang="ts">
	import { Button } from 'carbon-components-svelte';
	import DocumentAddIcon from 'carbon-icons-svelte/lib/DocumentAdd.svelte';
	import RotateIcon from 'carbon-icons-svelte/lib/Rotate.svelte';
	import CopyIcon from 'carbon-icons-svelte/lib/Copy.svelte';
	import DocumentBlankIcon from 'carbon-icons-svelte/lib/DocumentBlank.svelte';
	import TrashCanIcon from 'carbon-icons-svelte/lib/TrashCan.svelte';
	import SplitScreenIcon from 'carbon-icons-svelte/lib/SplitScreen.svelte';
	import CompressIcon from 'carbon-icons-svelte/lib/Minimize.svelte';
	import UndoIcon from 'carbon-icons-svelte/lib/Undo.svelte';
	import RedoIcon from 'carbon-icons-svelte/lib/Redo.svelte';
	import DownloadIcon from 'carbon-icons-svelte/lib/Download.svelte';
	import PrinterIcon from 'carbon-icons-svelte/lib/Printer.svelte';
	import ShareIcon from 'carbon-icons-svelte/lib/Share.svelte';
	import CheckboxCheckedIcon from 'carbon-icons-svelte/lib/CheckboxChecked.svelte';

	interface Props {
		pageCount: number;
		selectedCount: number;
		canUndo: boolean;
		canRedo: boolean;
		isLoading: boolean;
		maxPages: number;
		onadd: () => void;
		onrotate: () => void;
		onduplicate: () => void;
		oninsertblank: () => void;
		ondelete: () => void;
		onsplit: () => void;
		oncompress: () => void;
		onundo: () => void;
		onredo: () => void;
		onexport: () => void;
		onprint: () => void;
		onshare: () => void;
		onselectall: () => void;
	}

	let {
		pageCount,
		selectedCount,
		canUndo,
		canRedo,
		isLoading,
		maxPages,
		onadd,
		onrotate,
		onduplicate,
		oninsertblank,
		ondelete,
		onsplit,
		oncompress,
		onundo,
		onredo,
		onexport,
		onprint,
		onshare,
		onselectall
	}: Props = $props();

	let atPageLimit = $derived(pageCount >= maxPages);

	let noSelection = $derived(selectedCount === 0);
	let noPages = $derived(pageCount === 0);
</script>

<div class="toolbar" role="toolbar" aria-label="Page operations" aria-orientation="horizontal">
	<div class="toolbar-group">
		<Button
			kind="ghost"
			size="small"
			icon={DocumentAddIcon}
			iconDescription="Add files"
			disabled={isLoading}
			on:click={onadd}
		><span class="btn-label">Add</span></Button>
		<Button
			kind="ghost"
			size="small"
			icon={CheckboxCheckedIcon}
			iconDescription="Select all"
			disabled={noPages}
			on:click={onselectall}
		><span class="btn-label">Select All</span></Button>
	</div>
	<div class="toolbar-divider"></div>
	<div class="toolbar-group">
		<Button
			kind="ghost"
			size="small"
			icon={RotateIcon}
			iconDescription="Rotate"
			disabled={noSelection}
			on:click={onrotate}
		><span class="btn-label">Rotate</span></Button>
		<Button
			kind="ghost"
			size="small"
			icon={CopyIcon}
			iconDescription="Duplicate"
			disabled={noSelection}
			on:click={onduplicate}
		><span class="btn-label">Duplicate</span></Button>
		<Button
			kind="ghost"
			size="small"
			icon={DocumentBlankIcon}
			iconDescription="Insert blank page"
			disabled={atPageLimit || isLoading}
			on:click={oninsertblank}
		><span class="btn-label">Blank</span></Button>
		<Button
			kind="ghost"
			size="small"
			icon={TrashCanIcon}
			iconDescription="Delete"
			disabled={noSelection}
			on:click={ondelete}
		><span class="btn-label">Delete</span></Button>
	</div>
	<div class="toolbar-divider"></div>
	<div class="toolbar-group">
		<Button
			kind="ghost"
			size="small"
			icon={SplitScreenIcon}
			iconDescription="Split"
			disabled={noPages}
			on:click={onsplit}
		><span class="btn-label">Split</span></Button>
		<Button
			kind="ghost"
			size="small"
			icon={CompressIcon}
			iconDescription="Compress"
			disabled={noSelection}
			on:click={oncompress}
		><span class="btn-label">Compress</span></Button>
	</div>
	<div class="toolbar-spacer"></div>
	<div class="toolbar-group">
		<Button
			kind="ghost"
			size="small"
			icon={UndoIcon}
			iconDescription="Undo"
			disabled={!canUndo}
			on:click={onundo}
		/>
		<Button
			kind="ghost"
			size="small"
			icon={RedoIcon}
			iconDescription="Redo"
			disabled={!canRedo}
			on:click={onredo}
		/>
	</div>
	<div class="toolbar-group">
		<Button
			kind="primary"
			size="small"
			icon={DownloadIcon}
			disabled={noPages || isLoading}
			on:click={onexport}
		><span class="btn-label">Export</span></Button>
		<Button
			kind="ghost"
			size="small"
			icon={PrinterIcon}
			iconDescription="Print"
			disabled={noPages || isLoading}
			on:click={onprint}
		><span class="btn-label">Print</span></Button>
		<Button
			kind="ghost"
			size="small"
			icon={ShareIcon}
			iconDescription="Share"
			disabled={noPages || isLoading}
			on:click={onshare}
		><span class="btn-label">Share</span></Button>
	</div>
</div>

<style>
	.toolbar {
		display: flex;
		align-items: center;
		gap: 4px;
		padding: 8px 0;
		border-top: 1px solid var(--cds-border-subtle-01, #262626);
		border-bottom: 1px solid var(--cds-border-subtle-01, #262626);
		flex-wrap: wrap;
	}

	.toolbar-group {
		display: flex;
		align-items: center;
		gap: 2px;
	}

	.toolbar-divider {
		width: 1px;
		height: 24px;
		background: var(--cds-border-subtle-01, #262626);
		margin: 0 4px;
	}

	.toolbar-spacer {
		flex: 1;
	}

	@media (max-width: 671px) {
		.toolbar {
			gap: 2px;
		}

		.btn-label {
			display: none;
		}
	}
</style>
