// src/components/scanner/PageGallery.tsx
import { useCallback } from 'react';
import {
  DndContext,
  closestCenter,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent
} from '@dnd-kit/core';
import {
  SortableContext,
  horizontalListSortingStrategy,
  useSortable,
  arrayMove
} from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { Button } from '@carbon/react';
import { Download, Image as ImageIcon, ArrowRight, Close } from '@carbon/icons-react';
import type { ScannedPage } from '@/stores/scanner';
import { useScannerStore } from '@/stores/scanner';
import './PageGallery.css';

interface PageGalleryProps {
  pages: ScannedPage[];
  maxPages: number;
  onEdit: (id: string) => void;
  onDelete: (id: string) => void;
  onExport: () => void;
  onExportImages?: () => void;
  onManipulator: () => void;
}

interface SortableThumbProps {
  page: ScannedPage;
  index: number;
  onEdit: (id: string) => void;
  onDelete: (id: string) => void;
}

function SortableThumb({ page, index, onEdit, onDelete }: SortableThumbProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging
  } = useSortable({ id: page.id });

  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      {...attributes}
      {...listeners}
      className={`thumb-card${isDragging ? ' dragging' : ''}`}
      role="button"
      tabIndex={0}
      onClick={() => onEdit(page.id)}
      onKeyDown={(e) => { if (e.key === 'Enter') onEdit(page.id); }}
      aria-label={`Page ${index + 1} — tap to edit`}
    >
      <img src={page.thumbnail} alt={`Page ${index + 1}`} className="thumb-img" />
      <span className="page-badge">{index + 1}</span>
      <button
        className="delete-btn"
        onClick={(e) => { e.stopPropagation(); onDelete(page.id); }}
        aria-label={`Delete page ${index + 1}`}
      >
        <Close size={14} />
      </button>
    </div>
  );
}

/** Horizontal scrollable page gallery with DnD reorder, export, and manipulator actions */
export default function PageGallery({ pages, maxPages, onEdit, onDelete, onExport, onExportImages, onManipulator }: PageGalleryProps) {
  const reorderPages = useScannerStore((s) => s.reorderPages);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 8 } })
  );

  const handleDragEnd = useCallback((event: DragEndEvent) => {
    const { active, over } = event;
    if (!over || active.id === over.id) return;

    const oldIndex = pages.findIndex((p) => p.id === active.id);
    const newIndex = pages.findIndex((p) => p.id === over.id);
    if (oldIndex === -1 || newIndex === -1) return;

    reorderPages(arrayMove(pages, oldIndex, newIndex));
  }, [pages, reorderPages]);

  if (pages.length === 0) {
    return (
      <div className="page-gallery">
        <div className="empty-state">
          <p>No pages scanned yet. Capture your first page to get started.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="page-gallery">
      <div className="counter">
        {pages.length} / {maxPages} pages
      </div>

      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
        <SortableContext items={pages.map((p) => p.id)} strategy={horizontalListSortingStrategy}>
          <div className="thumbnail-strip" role="list">
            {pages.map((page, i) => (
              <SortableThumb
                key={page.id}
                page={page}
                index={i}
                onEdit={onEdit}
                onDelete={onDelete}
              />
            ))}
          </div>
        </SortableContext>
      </DndContext>

      <div className="actions">
        <Button kind="primary" size="sm" renderIcon={Download} onClick={onExport}>
          Export as PDF
        </Button>
        {onExportImages && (
          <Button kind="tertiary" size="sm" renderIcon={ImageIcon} onClick={onExportImages}>
            Save as Images
          </Button>
        )}
        <Button kind="secondary" size="sm" renderIcon={ArrowRight} onClick={onManipulator}>
          Open in Manipulator
        </Button>
      </div>
    </div>
  );
}

// src/lib/components/scanner/PageGallery.svelte
<script lang="ts">
	import { dndzone } from 'svelte-dnd-action';
	import { Button } from 'carbon-components-svelte';
	import Download from 'carbon-icons-svelte/lib/Download.svelte';
	import Image from 'carbon-icons-svelte/lib/Image.svelte';
	import ArrowRight from 'carbon-icons-svelte/lib/ArrowRight.svelte';
	import Close from 'carbon-icons-svelte/lib/Close.svelte';
	import type { ScannedPage } from '$lib/stores/scanner.svelte';
	import { reorderPages } from '$lib/stores/scanner.svelte';

	interface Props {
		pages: ScannedPage[];
		maxPages: number;
		onedit: (id: string) => void;
		ondelete: (id: string) => void;
		onexport: () => void;
		onexportimages?: () => void;
		onmanipulator: () => void;
	}

	let { pages, maxPages, onedit, ondelete, onexport, onexportimages, onmanipulator }: Props = $props();

	const flipDurationMs = 200;

	function handleDndConsider(e: CustomEvent<{ items: ScannedPage[] }>) {
		pages = e.detail.items;
	}

	function handleDndFinalize(e: CustomEvent<{ items: ScannedPage[] }>) {
		reorderPages(e.detail.items);
	}
</script>

<div class="page-gallery">
	{#if pages.length === 0}
		<div class="empty-state">
			<p>No pages scanned yet. Capture your first page to get started.</p>
		</div>
	{:else}
		<div class="counter">
			{pages.length} / {maxPages} pages
		</div>

		<div
			class="thumbnail-strip"
			role="list"
			use:dndzone={{ items: pages, flipDurationMs, type: 'scanner-pages' }}
			onconsider={handleDndConsider}
			onfinalize={handleDndFinalize}
		>
			{#each pages as page, i (page.id)}
				<div
					class="thumb-card"
					role="button"
					tabindex="0"
					onclick={() => onedit(page.id)}
					onkeydown={(e) => { if (e.key === 'Enter') onedit(page.id); }}
					aria-label="Page {i + 1} — tap to edit"
				>
					<img src={page.thumbnail} alt="Page {i + 1}" class="thumb-img" />
					<span class="page-badge">{i + 1}</span>
					<button
						class="delete-btn"
						onclick={(e) => { e.stopPropagation(); ondelete(page.id); }}
						aria-label="Delete page {i + 1}"
					>
						<Close size={14} />
					</button>
				</div>
			{/each}
		</div>

		<div class="actions">
			<Button kind="primary" size="small" icon={Download} on:click={onexport}>
				Export as PDF
			</Button>
			{#if onexportimages}
				<Button kind="tertiary" size="small" icon={Image} on:click={onexportimages}>
					Save as Images
				</Button>
			{/if}
			<Button kind="secondary" size="small" icon={ArrowRight} on:click={onmanipulator}>
				Open in Manipulator
			</Button>
		</div>
	{/if}
</div>

<style>
	.page-gallery {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
		padding: 0.5rem;
		background: var(--cds-layer-01, #0d0d0d);
	}

	.empty-state {
		padding: 2rem 1rem;
		text-align: center;
		color: var(--cds-text-secondary, #c6c6c6);
		font-family: var(--sf-font-body);
		font-size: 0.875rem;
	}

	.counter {
		font-family: var(--sf-font-body);
		font-size: 0.75rem;
		color: var(--cds-text-secondary, #c6c6c6);
		padding: 0 0.25rem;
	}

	.thumbnail-strip {
		display: flex;
		gap: 0.5rem;
		overflow-x: auto;
		overflow-y: hidden;
		padding: 0.25rem 0;
		scroll-snap-type: x mandatory;
		-webkit-overflow-scrolling: touch;
		scrollbar-width: none;
	}

	.thumbnail-strip::-webkit-scrollbar {
		display: none;
	}

	.thumb-card {
		flex-shrink: 0;
		width: 80px;
		height: 100px;
		position: relative;
		border: 2px solid var(--cds-border-subtle-01, #262626);
		border-radius: var(--sf-radius-sm, 8px);
		overflow: hidden;
		background: var(--cds-layer-02, #1a1a1a);
		cursor: pointer;
		scroll-snap-align: start;
		padding: 0;
		-webkit-tap-highlight-color: transparent;
	}

	.thumb-card:hover {
		border-color: var(--cds-interactive, #0f62fe);
	}

	.thumb-img {
		width: 100%;
		height: 100%;
		object-fit: cover;
		display: block;
	}

	.page-badge {
		position: absolute;
		bottom: 4px;
		left: 4px;
		font-family: var(--sf-font-body);
		font-size: 0.625rem;
		color: var(--cds-text-on-color, #fff);
		background: rgba(0, 0, 0, 0.7);
		padding: 1px 5px;
		border-radius: 24px;
		line-height: 1.3;
	}

	.delete-btn {
		position: absolute;
		top: 2px;
		right: 2px;
		width: 22px;
		height: 22px;
		border-radius: 50%;
		border: none;
		background: rgba(0, 0, 0, 0.7);
		color: var(--cds-text-primary, #f4f4f4);
		display: flex;
		align-items: center;
		justify-content: center;
		cursor: pointer;
		padding: 0;
	}

	.delete-btn:hover {
		background: var(--cds-button-danger-primary, #da1e28);
	}

	.actions {
		display: flex;
		gap: 0.5rem;
		flex-wrap: wrap;
		padding: 0.25rem 0;
	}
</style>
